## Data Exploration ##

In [7]:
# Import libraries
import duckdb
import pandas as pd
import os

In [8]:
# Load Data
db = duckdb.connect(database='../Data/jaffle_shop.duckdb')

In [9]:
db.execute("SHOW TABLES").df()

          name
0    customers
1  order_items
2       orders
3     products

In [10]:
db.execute("DESCRIBE customers").df()

    column_name column_type null  key default extra
0   customer_id     INTEGER   NO  PRI    None  None
1    first_name     VARCHAR   NO  NaN    None  None
2     last_name     VARCHAR   NO  NaN    None  None
3         email     VARCHAR  YES  NaN    None  None
4  loyalty_tier     VARCHAR  YES  NaN    None  None
5    created_at   TIMESTAMP   NO  NaN    None  None

In [11]:
db.execute("DESCRIBE order_items").df()

     column_name    column_type null  key default extra
0  order_item_id        INTEGER   NO  PRI    None  None
1       order_id        INTEGER   NO  NaN    None  None
2     product_id        INTEGER   NO  NaN    None  None
3       quantity        INTEGER   NO  NaN    None  None
4     unit_price   DECIMAL(8,2)   NO  NaN    None  None
5     line_total  DECIMAL(10,2)   NO  NaN    None  None

In [12]:
db.execute("DESCRIBE orders").df()

     column_name    column_type null  key default extra
0       order_id        INTEGER   NO  PRI    None  None
1    customer_id        INTEGER   NO  NaN    None  None
2     order_date           DATE   NO  NaN    None  None
3         status        VARCHAR   NO  NaN    None  None
4   total_amount  DECIMAL(10,2)  YES  NaN    None  None
5  order_channel        VARCHAR  YES  NaN    None  None

In [13]:
db.execute("DESCRIBE products").df()

    column_name   column_type null  key default extra
0    product_id       INTEGER   NO  PRI    None  None
1  product_name       VARCHAR   NO  NaN    None  None
2      category       VARCHAR   NO  NaN    None  None
3         price  DECIMAL(8,2)   NO  NaN    None  None
4   description       VARCHAR  YES  NaN    None  None

In [14]:
# Lenght of each table
table_lengths = pd.DataFrame({
    "table_name": ["customers", "orders", "order_items", "products"],
    "length": [
        db.execute("SELECT COUNT(*) FROM customers").fetchone()[0],
        db.execute("SELECT COUNT(*) FROM orders").fetchone()[0],
        db.execute("SELECT COUNT(*) FROM order_items").fetchone()[0],
        db.execute("SELECT COUNT(*) FROM products").fetchone()[0]
    ]
})
table_lengths

    table_name  length
0    customers     200
1       orders    3000
2  order_items    6583
3     products      16

In [15]:
# Explore first 5 rows of each table
db.execute("SELECT * FROM customers LIMIT 5").df()

,customer_id,first_name,last_name,email,loyalty_tier,created_at
0,1,Hannah,Davis,hannah.davis1@example.com,bronze,2023-10-09
1,2,Henry,Anderson,henry.anderson2@example.com,bronze,2023-04-15
2,3,Caleb,Mitchell,caleb.mitchell3@example.com,gold,2023-03-31
3,4,Logan,Ramirez,logan.ramirez4@example.com,bronze,2023-04-06
4,5,Lucas,Anderson,lucas.anderson5@example.com,silver,2023-01-28

In [16]:
db.execute("SELECT * FROM order_items LIMIT 5").df()

   order_item_id  order_id  product_id  quantity  unit_price  line_total
0              1         1          14         1         3.5         3.5
1              2         1          12         1         6.0         6.0
2              3         2          11         1         4.5         4.5
3              4         2           2         2         9.0        18.0
4              5         2          12         1         6.0         6.0

In [17]:
db.execute("SELECT * FROM orders LIMIT 5").df()

   order_id  customer_id order_date     status  total_amount order_channel
0         1           79 2025-11-10  completed           9.5        online
1         2          117 2024-10-04  completed          28.5      in-store
2         3           56 2026-01-26  completed          39.5        online
3         4           33 2024-10-07  completed          24.5      in-store
4         5            4 2025-08-10  completed          28.0        online

In [18]:
db.execute("SELECT * FROM products LIMIT 5").df()

,product_id,product_name,category,price,description
0,1,Classic Jaffle,Jaffles,8.5,Our signature toasted sandwich with ham and ch...
1,2,Veggie Jaffle,Jaffles,9.0,Grilled vegetables with mozzarella and pesto
2,3,BBQ Chicken Jaffle,Jaffles,10.5,Pulled chicken with BBQ sauce and cheddar
3,4,Spicy Beef Jaffle,Jaffles,11.0,Seasoned beef with jalapeños and pepper jack
4,5,Mushroom & Brie Jaffle,Jaffles,10.0,Sautéed mushrooms with melted brie